name: Continuous Integration - Unit Testing

on:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
          cache: pip

      - name: Install requirement
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: python -m pip install --upgrade pip
             pip install tox tox-gh-actions

      - name: Run with tox
        run: tox

      - name: Run tests
        run: pytest -v -ra --disable-warnings unit_testing.py
